version: "3.1"
services:
  python:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bottlesite_container
    ports:
      - 80:80
    volumes:
      - ./:/app

  sqlite:
    image: nouchka/sqlite3
    container_name: bottlesite_sqlite_container
    volumes:
      - ./sqlite_data:/data
    command: tail -f /dev/null
